Add support for reading rootfs location
Rather than assume the root filesystem location, read the location from
the config.json and save it to a rootfs under the container run
directory.

Signed-off-by: Brian Woods <brian.woods@xilinx.com>
Reviewed-by: Stefano Stabellini <sstabellini@kernel.org>
Signed-off-by: Stefano Stabellini <stefano.stabellini@xilinx.com>

diff --git a/runX b/runX
--- a/runX
+++ b/runX
@@ -81,6 +81,19 @@ fi
 if test \( "$bundle" \) -a \( ! -f "$crundir"/bundle \)
 then
     echo -n "$bundle" > "$crundir"/bundle
+
+    if  test -f "$bundle"/config.json
+    then
+        rootfs="$( jq -r -c  '.["root"]["path"]' "$bundle"/config.json )"
+        if [[ "$rootfs" != /* ]]
+        then
+            rootfs="$bundle"/"$rootfs"
+        fi
+        echo -n "$rootfs" > "$crundir"/rootfs
+    else
+        echo "can't determine rootfs, erring out"
+        exit 1
+    fi
 fi
 
 if test \( "$pidfile" \) -a \( ! -f "$crundir"/pidfile \)
